export enum AirdropEligibilityStatus {
  ELIGIBLE = 'ELIGIBLE',
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
  CLAIMABLE = 'CLAIMABLE',
  CLAIMED = 'CLAIMED',
  AUTO_DROP = 'AUTO_DROP',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
}
