export enum GetterTypes {
  getKeplr = 'getKeplr',
  getGasLimit = 'getGasLimit',
  isSignedIn = 'isSignedIn',
  getKeyhashes = 'getKeyhashes',
  getKeplrAccountName = 'getKeplrAccountName',
  isDemoAccount = 'isDemoAccount',
  hasSeenReedem = 'hasSeenReedem',
  viewUnverified = 'viewUnverified',
  viewLPAssetPools = 'viewLPAssetPools',
  allowCustomSlippage = 'allowCustomSlippage',
  getKeplrAddress = 'getKeplrAddress',
  getSlippagePerc = 'getSlippagePerc',
  theme = 'theme',
  getPreferredGasPriceLevel = 'getPreferredGasPriceLevel',
  getOwnAddress = 'getOwnAddress',
}
export enum GlobalGetterTypes {
  getKeplr = 'demerisUSER/getKeplr',
  getGasLimit = 'demerisUSER/getGasLimit',
  isSignedIn = 'demerisUSER/isSignedIn',
  getKeyhashes = 'demerisUSER/getKeyhashes',
  getKeplrAccountName = 'demerisUSER/getKeplrAccountName',
  isDemoAccount = 'demerisUSER/isDemoAccount',
  hasSeenReedem = 'demerisUSER/hasSeenReedem',
  viewUnverified = 'demerisUSER/viewUnverified',
  viewLPAssetPools = 'demerisUSER/viewLPAssetPools',
  allowCustomSlippage = 'demerisUSER/allowCustomSlippage',
  getKeplrAddress = 'demerisUSER/getKeplrAddress',
  getSlippagePerc = 'demerisUSER/getSlippagePerc',
  theme = 'demerisUSER/theme',
  getPreferredGasPriceLevel = 'demerisUSER/getPreferredGasPriceLevel',
  getOwnAddress = 'demerisUSER/getOwnAddress',
}
