export enum GetterTypes {
  getAccount = 'getAccount',
  getChainKeyData = 'getChainKeyData',
  getFirstLoad = 'getFirstLoad',
  getPricesFirstLoad = 'getPricesFirstLoad',
  getStakingBalancesFirstLoad = 'getStakingBalancesFirstLoad',
  getBalancesFirstLoad = 'getBalancesFirstLoad',
  getCorrelationId = 'getCorrelationId',
  getGasLimit = 'getGasLimit',
  isSignedIn = 'isSignedIn',
  getKeyhashes = 'getKeyhashes',
  isDemoAccount = 'isDemoAccount',
  hasSeenReedem = 'hasSeenReedem',
  viewUnverified = 'viewUnverified',
  viewLPAssetPools = 'viewLPAssetPools',
  allowCustomSlippage = 'allowCustomSlippage',
  getSlippagePerc = 'getSlippagePerc',
  theme = 'theme',
  getPreferredGasPriceLevel = 'getPreferredGasPriceLevel',
  isAllBalancesLoaded = 'isAllBalancesLoaded',
}
export enum GlobalGetterTypes {
  getAccount = 'demerisUSER/getAccount',
  getChainKeyData = 'demerisUSER/getChainKeyData',
  getFirstLoad = 'demerisUSER/getFirstLoad',
  getPricesFirstLoad = 'demerisUSER/getPricesFirstLoad',
  getStakingBalancesFirstLoad = 'demerisUSER/getStakingBalancesFirstLoad',
  getBalancesFirstLoad = 'demerisUSER/getBalancesFirstLoad',
  getCorrelationId = 'demerisUSER/getCorrelationId',
  getGasLimit = 'demerisUSER/getGasLimit',
  isSignedIn = 'demerisUSER/isSignedIn',
  getKeyhashes = 'demerisUSER/getKeyhashes',
  isDemoAccount = 'demerisUSER/isDemoAccount',
  hasSeenReedem = 'demerisUSER/hasSeenReedem',
  viewUnverified = 'demerisUSER/viewUnverified',
  viewLPAssetPools = 'demerisUSER/viewLPAssetPools',
  allowCustomSlippage = 'demerisUSER/allowCustomSlippage',
  getSlippagePerc = 'demerisUSER/getSlippagePerc',
  theme = 'demerisUSER/theme',
  getPreferredGasPriceLevel = 'demerisUSER/getPreferredGasPriceLevel',
  isAllBalancesLoaded = 'demerisUSER/isAllBalancesLoaded',
}
