export enum MutationTypes {
  ADD_KEPLR_KEYHASH = 'ADD_KEPLR_KEYHASH',
  SET_KEPLR = 'SET_KEPLR',
  SET_SESSION_DATA = 'SET_SESSION_DATA',
  SET_GAS_LIMIT = 'SET_GAS_LIMIT',
  SET_BALANCES_FIRST_LOAD = 'SET_BALANCES_FIRST_LOAD',
  SET_STAKING_BALANCES_FIRST_LOAD = 'SET_STAKING_BALANCES_FIRST_LOAD',
  SET_PRICES_FIRST_LOAD = 'SET_PRICES_FIRST_LOAD',
  SET_CORRELATION_ID = 'SET_CORRELATION_ID',
  SIGN_OUT = 'SIGN_OUT',
  RESET_STATE = 'RESET_STATE',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
}
