export enum MutationTypes {
  ADD_CHAIN_KEY_DATA = 'ADD_CHAIN_KEY_DATA',
  SET_ACCOUNT = 'SET_ACCOUNT',
  SET_SESSION_DATA = 'SET_SESSION_DATA',
  SET_GAS_LIMIT = 'SET_GAS_LIMIT',
  SET_BALANCES_FIRST_LOAD = 'SET_BALANCES_FIRST_LOAD',
  SET_STAKING_BALANCES_FIRST_LOAD = 'SET_STAKING_BALANCES_FIRST_LOAD',
  SET_PRICES_FIRST_LOAD = 'SET_PRICES_FIRST_LOAD',
  SET_CORRELATION_ID = 'SET_CORRELATION_ID',
  SIGN_OUT = 'SIGN_OUT',
  RESET_STATE = 'RESET_STATE',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
}
