name: Deploy to Preview Channel

on: pull_request

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: NODE_OPTIONS="--max_old_space_size=8192" yarn build:production

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERIS_HQ }}"
          target: prod
          expires: 7d
          projectId: emeris-hq
