name: Deploy to Production

on:
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      enable_maintenance_screen:
        description: Enable maintenance screen
        required: true
        default: "false"
      empty_out_dir:
        description: Clear dist folder before build
        required: true
        default: false
        type: boolean

env:
  VITE_FEATURE_MAINTENANCE_SCREEN: ${{ github.event.inputs.enable_maintenance_screen || 'false' }}

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: NODE_OPTIONS="--max_old_space_size=8192" npm run build:production -- --emptyOutDir ${{ github.event.inputs.empty_out_dir }}

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERIS_HQ }}"
          target: prod
          channelId: live
          projectId: emeris-hq
