name: Generate static demo-account.js

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  
jobs:
  generate-demo-accounts-file:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run generate:demo-acounts
      env:
        DEMO_ACCOUNT_MNEMONIC: ${{ secrets.DEMO_ACCOUNT_MNEMONIC }}
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-generate /src/store/demeris-user/demo-account.js