name: Playwright Tests
on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches: [ production ]

env:
  VUE_APP_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}

jobs:
  test:
    
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 60
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps    
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Netlify
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Pages changed - emeris-app'
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Wait for deploy preview
        if: steps.wait-for-Netlify.outputs.conclusion == 'neutral'
        uses: jakepartusch/wait-for-netlify-action@v1.3
        id: waitFor200
        with:
          site_name: "emeris-app"  
      - name: Run Playwright tests
        run: npx playwright test
        env: 
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
