name: Playwright Tests
on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches: [ production ]

env:
  VUE_APP_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}

jobs:
  test:
    
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 60
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.3
        id: waitFor200
        with:
          site_name: "emeris"
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Serve build
        run: serve -s dist -l 8080
      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
