name: Playwright Tests
on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches: [ production ]

env:
  VUE_APP_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}

jobs:
  test:
    
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 60
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Install Serve
        run: npm install -g serve
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Run Playwright tests
        run: 
          serve -s dist -l 8080 &
          npx playwright test
        env: 
          PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:8080'

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
