name: Unit & E2E

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches:
      - develop

env:
  VUE_APP_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}
  VUE_APP_FEATURE_USE_DEV: true

jobs:
  unit:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
  
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Test
        run: npm run test:unit -- --runInBand

  e2e:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Update system
        run: sudo apt update

      - name: Install dependencies
        run: sudo DEBIAN_FRONTEND=noninteractive apt -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 180

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots