name: Build & Test

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: apt update
        run: sudo apt update

      - name: install dependencies
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm install

      # - name: install image-snapshot plugin
      #   run: npm -f install --save-dev cypress-image-snapshot

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: VUE_APP_EMERIS_MNEMONIC=${{ secrets.VUE_APP_EMERIS_MNEMONIC }}
          start: npm run serve
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 180

      - name: Test
        run: npm run test:unit -- --runInBand
