name: Build & Test

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          VUE_APP_EMERIS_MNEMONIC: ${{secrets.VUE_APP_EMERIS_MNEMONIC}}

      - name: apt update
        run: sudo apt update

      - name: install dependencies
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Cypress run
        uses: cypress-io/github-action@v2

      - name: Test
        run: npm run test:unit -- --runInBand
