name: Unit & E2E

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches:
      - develop
  schedule:
    - cron: '0,30 * * * *'

env:
  VITE_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
  
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock

      - name: Install (yarn)
        run: yarn

      - name: Test
        run: yarn test:unit

  e2e:
    
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 60
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock

      - name: Install (yarn)
        run: yarn

      - name: Install Serve
        run: npm install -g serve
      
      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Build
        run: yarn build:production

      - name: Run Playwright tests
        run: 
          serve -s dist -l 8080 &
          npx playwright test
        env: 
          PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:8080'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
