name: Build & Test

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    env:
      VUE_APP_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}
      VUE_APP_FEATURE_USE_DEV: true

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: apt update
        run: sudo apt update
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 180

      - name: Test
        run: npm run test:unit -- --runInBand
