name: Unit & E2E

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches:
      - develop
  schedule:
    - cron: '0,30 * * * *'

env:
  VUE_APP_EMERIS_MNEMONIC: ${{ secrets.VUE_APP_EMERIS_MNEMONIC }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
  
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Test
        run: npm run test:unit -- --runInBand

  e2e:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Update system
        run: sudo apt update

      - name: Install dependencies
        run: sudo DEBIAN_FRONTEND=noninteractive apt -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Netlify
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Pages changed - emeris-app'
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Wait for deploy preview
        if: steps.wait-for-Netlify.outputs.conclusion == 'neutral'
        uses: jakepartusch/wait-for-netlify-action@v1.3
        id: waitFor200
        with:
          site_name: "emeris-app"

      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        with:
          wait-on: ${{ steps.waitFor200.outputs.url }}
          wait-on-timeout: 10
        env:
          CYPRESS_BASE_URL: ${{ steps.waitFor200.outputs.url }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Notify Slack
        if: |
          failure() &&
          github.event.schedule == '0,30 * * * *'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: emeris-frontend-github
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'See results at ${{ steps.cypress.outputs.dashboardUrl }}'
          SLACK_TITLE: 'Cypress finished with: ${{ steps.cypress.outcome }}'
          SLACK_USERNAME: E2E test bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
